name: Build and Deploy UniApp H5

on:
  push:
    branches:
      - main

jobs:
  build-h5:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download HBuilderX
        run: |
          curl -L -o hbuilderx.zip https://github.com/GmhLovEDM/hbuilderx/releases/download/4.87/HBuilderX.4.87.2025121004.zip
          mkdir HBuilderX
          7z x hbuilderx.zip -oHBuilderX

      - name: Build UniApp H5
        shell: cmd
        run: |
          ".\HBuilderX\HBuilderX\cli.exe" publish --platform h5 --project .\

      - name: List project files
        run: dir

      - name: Upload H5 build artifact
        uses: actions/upload-artifact@v4
        with:
          name: h5-dist
          path: unpackage/dist/build/web/

  # ------------------------
  # 2️⃣ Linux: 部署到服务器
  # ------------------------
  deploy-h5:
    runs-on: ubuntu-latest
    needs: build-h5

    steps:
      - name: Download H5 build artifact
        uses: actions/download-artifact@v4
        with:
          name: h5-dist
          path: ./deploy

      - name: List deploy folder (debug)
        run: ls -R ./deploy

      - name: Deploy via rsync
        uses: burnett01/rsync-deployments@7.0.1
        with:
          switches: -avz --delete --exclude=".*"
          path: ./deploy
          remote_path: /www/wwwroot/demo.seeuui.cn/
          remote_host: ${{ secrets.SERVER_HOST }}
          remote_user: ${{ secrets.SERVER_USER }}
          remote_key: ${{ secrets.SERVER_SSH_KEY }}
